project_id = "impgemzhqvbxitsxxczm"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
    import_map = "./functions/auth-email-hook/deno.json"
  [functions.check-account-method]
    verify_jwt = false
  [functions.generate-receipt]
    verify_jwt = true
  [functions.generate-sitemap]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.youcanpay-create-token]
    verify_jwt = true
  [functions.youcanpay-verify-payment]
    verify_jwt = true
  [functions.youcanpay-webhook]
    verify_jwt = false
